#!/usr/bin/env python3
"""
v1 pipeline orchestrator.

Runs the full "v1 manuscript objectives" execution pipeline end-to-end, in
dependency order, at the scale configured in config/v1_pipeline.yaml. Each stage
is a standalone script; this runner executes them as subprocesses, reports
pass/fail and timing, and writes results/v1/README.md summarizing the outputs
(with the SYNTHETIC-data disclaimer).

Usage:
    python scripts/run_v1_pipeline.py            # run all stages
    python scripts/run_v1_pipeline.py --from 5   # resume from stage 5
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
import time
from pathlib import Path

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.abspath(os.path.join(_HERE, ".."))
sys.path.insert(0, _HERE)
import v1_common as vc  # noqa: E402

# (stage number, human label, script relative to repo root)
STAGES = [
    (1, "Calibration check vs literature targets", "scripts/calibration/calibrate_expanded_model.py"),
    (2, "Incidence by drug & class", "scripts/analysis/class_incidence.py"),
    (3, "Biphasic / temporal dynamics", "scripts/analysis/biphasic_temporal.py"),
    (3, "Autoantibody seroconversion", "scripts/analysis/seroconversion.py"),
    (4, "Global sensitivity (Morris + Sobol)", "scripts/sensitivity/global_sensitivity_analysis.py"),
    (5, "Synthetic cohorts", "scripts/cohorts/generate_synthetic_cohorts.py"),
    (6, "Internal & external validation", "scripts/validation/internal_external_validation.py"),
    (7, "Virtual population", "scripts/population/virtual_population.py"),
    (8, "ML ensemble", "scripts/ml/ensemble_classifier.py"),
    (8, "Biomarker odds ratios", "scripts/analysis/biomarker_odds_ratios.py"),
    (8, "External benchmark fetch (FAERS)", "scripts/validation/fetch_faers_benchmarks.py"),
    (8, "External benchmark validation (literature + FAERS)", "scripts/validation/external_benchmark_validation.py"),
    (9, "Figures", "scripts/figures/generate_v1_figures.py"),
]

README = """# v1 Pipeline Results (IN-SILICO)

> **These outputs are model-generated, not real patient data.** They *execute*
> the objectives described in "Manuscript v.1" — a mechanistic QSP model with
> CTLA-4/combination therapy, biphasic dynamics, autoantibody seroconversion,
> global sensitivity analysis, virtual population, validation cohorts, and an ML
> ensemble. They are in-silico results, not empirical clinical findings.

**Calibration.** The expanded model (`qsp_expanded/`) is CALIBRATED so that
180-day per-drug hypothyroidism incidence lands in published ranges with correct
class ordering (Combination > PD-1 > PD-L1 > CTLA-4) and 60-140 day onset — see
`calibration_report.json`. The **epidemiological** outputs (incidence by class,
virtual population, sensitivity) reflect this calibrated population.

**Cohorts are covariate-sampled.** The `cohort_*.csv` used for the ML /
validation / odds-ratio stages sample each patient's susceptibility from their
risk factors (age, sex, HLA-DQ, baseline TSH) plus a random effect, giving a
12-month event rate (~12-19%) modestly higher than the marginal calibrated
population incidence (mild covariate risk enrichment). This is noted in the
cohort generator docstring.

Generated by `scripts/run_v1_pipeline.py` at the scale in
`config/v1_pipeline.yaml`.

## Outputs

| Area | Files |
|------|-------|
| Calibration check | `calibration_report.json` |
| Incidence by drug/class | `incidence_by_drug.csv`, `incidence_by_class.csv`, `class_risk_stats.json` |
| Biphasic / temporal | `biphasic_temporal_by_class.csv`, `biphasic_temporal.json` |
| Seroconversion | `seroconversion_by_class.csv`, `seroconversion_kinetics.csv`, `seroconversion.json` |
| Global sensitivity | `gsa_morris.csv`, `gsa_sobol.csv`, `gsa_summary.json` |
| Synthetic cohorts | `cohort_calibration.csv`, `cohort_external.csv`, `cohorts_summary.json` |
| Validation | `validation_internal.json`, `validation_external.json`, `validation_vpc.csv` |
| Virtual population | `virtual_population.csv`, `virtual_population_summary.json` |
| ML ensemble | `ml_ensemble_metrics.json` |
| Biomarker odds ratios | `biomarker_odds_ratios.csv`, `biomarker_odds_ratios.json` |
| External validation (held-out) | `external_faers_benchmarks.json` (real FDA FAERS), `external_validation_scorecard.json`, `external_validation_scorecard.csv` |
| Figures | `figures/*.png` |

## Reproduce

```
python scripts/run_v1_pipeline.py
```

Edit `config/v1_pipeline.yaml` to change scale (default is reduced-but-real;
full-scale magnitudes are noted inline in that file).
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--from", dest="from_stage", type=int, default=0,
                    help="skip stages numbered below this")
    args = ap.parse_args()

    vc.banner("v1 pipeline orchestrator")
    results = []
    for stage_no, label, script in STAGES:
        if stage_no < args.from_stage:
            print(f"  [skip] stage {stage_no}: {label}")
            continue
        print(f"\n  [stage {stage_no}] {label}  ({script})")
        t0 = time.time()
        proc = subprocess.run([sys.executable, os.path.join(_ROOT, script)],
                              cwd=_ROOT, capture_output=True, text=True)
        dt = time.time() - t0
        ok = proc.returncode == 0
        tail = "\n".join(l for l in proc.stdout.splitlines()
                         if l.strip() and "Logging" not in l and "Log file" not in l
                         and "Console output" not in l)[-500:]
        print(f"    {'OK' if ok else 'FAIL'} in {dt:.0f}s")
        if not ok:
            print("    --- stderr tail ---")
            print("    " + "\n    ".join(proc.stderr.splitlines()[-8:]))
        results.append((stage_no, label, ok, round(dt, 1)))

    # Write README
    cfg = vc.load_config()
    out_dir = vc.output_dir(cfg)
    (out_dir / "README.md").write_text(README, encoding="utf-8")

    vc.banner("Pipeline summary")
    for stage_no, label, ok, dt in results:
        print(f"  [{'OK ' if ok else 'FAIL'}] stage {stage_no}: {label} ({dt}s)")
    n_ok = sum(1 for *_, ok, _ in results)
    print(f"\n  {n_ok}/{len(results)} stages succeeded. Wrote {out_dir/'README.md'}.")
    sys.exit(0 if n_ok == len(results) else 1)


if __name__ == "__main__":
    main()
