#!/usr/bin/env python3
"""
v1 Pipeline — Shared Utilities
==============================

Common helpers for the "v1 manuscript objectives" execution pipeline: config
loading, output-path management, RNG seeding, JSON/CSV writing with a mandatory
SYNTHETIC-data provenance stamp, and a small figure-saving helper.

Every artifact written through :func:`write_json` / :func:`write_csv` /
:func:`save_figure` carries a header noting it is IN-SILICO / SYNTHETIC output,
not derived from real patient data.
"""
from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any, Dict, Optional

import numpy as np
import pandas as pd
import yaml

# --- Repo / config paths ----------------------------------------------------
# scripts/v1_common.py  ->  repo root is one directory up.
REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = REPO_ROOT / "config" / "v1_pipeline.yaml"

SYNTHETIC_NOTICE = (
    "SYNTHETIC / IN-SILICO OUTPUT - generated by the QSP v1 execution pipeline "
    "(fixed seed; scale in config/v1_pipeline.yaml). Not derived from real patient "
    "data. The mechanistic model is calibrated to published per-drug "
    "hypothyroidism incidence ranges; cohort-based validation, machine-learning, "
    "and odds-ratio outputs are computed on model-generated cohorts. These are the "
    "values reported in the accompanying manuscript."
)


def load_config(path: Optional[os.PathLike] = None) -> Dict[str, Any]:
    """Load the v1 pipeline YAML config."""
    with open(path or CONFIG_PATH, "r", encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def output_dir(config: Dict[str, Any], *subdirs: str) -> Path:
    """Return (and create) an output directory under the configured root."""
    root = REPO_ROOT / config.get("output", {}).get("root", "results/v1")
    d = root.joinpath(*subdirs)
    d.mkdir(parents=True, exist_ok=True)
    return d


def rng(config: Dict[str, Any], offset: int = 0) -> np.random.Generator:
    """Return a seeded NumPy Generator (offset lets callers decorrelate streams)."""
    return np.random.default_rng(int(config.get("seed", 0)) + offset)


def _jsonable(obj: Any) -> Any:
    """Best-effort conversion of numpy/pandas types to JSON-serializable values."""
    if isinstance(obj, (np.integer,)):
        return int(obj)
    if isinstance(obj, (np.floating,)):
        return float(obj)
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    if isinstance(obj, (pd.Timestamp,)):
        return str(obj)
    return str(obj)


def write_json(path: os.PathLike, payload: Dict[str, Any]) -> Path:
    """Write a JSON file with a `_provenance` stamp prepended."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    stamped = {"_provenance": SYNTHETIC_NOTICE, **payload}
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(stamped, fh, indent=2, default=_jsonable)
    return path


def write_csv(path: os.PathLike, df: pd.DataFrame, note: str = "") -> Path:
    """Write a DataFrame to CSV with a leading `# SYNTHETIC ...` comment line."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as fh:
        fh.write(f"# {SYNTHETIC_NOTICE}\n")
        if note:
            fh.write(f"# {note}\n")
        df.to_csv(fh, index=False)
    return path


def save_figure(fig, path: os.PathLike, config: Dict[str, Any]) -> Path:
    """Save a matplotlib figure at the configured DPI and close it."""
    import matplotlib.pyplot as plt

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    dpi = int(config.get("output", {}).get("figure_dpi", 200))
    fig.savefig(path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)
    return path


def banner(title: str) -> None:
    """Print a consistent section banner to stdout."""
    line = "=" * 78
    print(f"\n{line}\n{title}\n{line}")
